Repository Goddard-Fortran-Ecosystem/gFTL, pull requests merged in 2025-01, with the labels that each got.

#234 Update CI - 2024-Aug-22
  .github/workflows/main.yml
  ChangeLog.MD
Labels: enhancement

#236 Fixes #235 missing TARGET on map::erase()
  .github/workflows/main.yml
  CMakeLists.txt
  ChangeLog.MD
  cmake/LLVMFlang.cmake
  include/v2/map/procedures.inc
  tests/map/Test_Map.m4
Labels: bug

#243 Fixes #242 - New container "alt_set".
  .github/workflows/main.yml
  ChangeLog.MD
  include/v2/CMakeLists.txt
  include/v2/algorithms/find/procedures.inc
  include/v2/algorithms/procedures.inc
  include/v2/alt_set/header.inc
  include/v2/alt_set/iterator_procedures.inc
  include/v2/alt_set/iterator_specification.inc
  include/v2/alt_set/procedures.inc
  include/v2/alt_set/public.inc
  include/v2/alt_set/specification.inc
  include/v2/alt_set/tail.inc
  include/v2/alt_set/template.inc
  include/v2/map/procedures.inc
  include/v2/map/specification.inc
  include/v2/parameters/CMakeLists.txt
  include/v2/set/procedures.inc
  include/v2/vector/iterator_specification.inc
  include/v2/vector/procedures.inc
  include/v2/vector/reverse_iterator_specification.inc
  include/v2/vector/specification.inc
  tests/CMakeLists.txt
  tests/alt_set/CMakeLists.txt
  tests/alt_set/Test_alt_set_Algorithms.m4
  tests/alt_set/alt_set.m4
  tests/map/CMakeLists.txt
  tests/map/Test_alt_MapAlgorithms.m4
  tests/map/alt_Map.m4
Labels: enhancement, workaround
